### ISSUE TITLE
Rule Seems to be Malformed, skipping

### ISSUE THREAD

**Issue by Mirac007** [JusticeRage/Manalyze#52] opened 2022-07-21 17:01 UTC
I get that when I run update_clamav_signatures.py. Cropped result of this is below:

Rule Win.Dropper.Zeus-9956976-0 seems to be malformed. Skipping...
Rule Win.Malware.Generic-9956990-0 seems to be malformed. Skipping...
Unable to translate a logical signature for Win.Malware.Wingo-9956993-0. Skipping...
Rule Win.Virus.Expiro-9957000-0 seems to be malformed. Skipping...
Rule Win.Dropper.Zeus-9957002-0 seems to be malformed. Skipping...
Rule Win.Packed.Vbkryjetor-9957003-0 seems to be malformed. Skipping...
Rule Win.Malware.Conjar-9957004-0 seems to be malformed. Skipping...
Rule Win.Dropper.Detected-9957005-0 seems to be malformed. Skipping...
Rule Win.Dropper.Detected-9957006-0 seems to be malformed. Skipping...
Rule Win.Packed.Trojanx-9957008-0 seems to be malformed. Skipping...
Rule Win.Packed.Coantor-9957009-0 seems to be malformed. Skipping...
Rule Win.Packed.Msilheracles-9957011-0 seems to be malformed. Skipping...
Rule Win.Trojan.Generic-9957017-0 seems to be malformed. Skipping...
Rule Win.Packed.Generickdz-9957018-0 seems to be malformed. Skipping...
Rule Win.Dropper.LokiBot-9957019-0 seems to be malformed. Skipping...
Rule Win.Virus.Ramnit-9957027-0 seems to be malformed. Skipping...
Rule Win.Dropper.LokiBot-9957036-0 seems to be malformed. Skipping...
Rule Win.Dropper.Zeus-9957041-0 seems to be malformed. Skipping...

It happens for all of the downloaded updates

**Comment by JusticeRage** [comment] 2022-07-21 23:01
Duplicate of #48.

**Closed by JusticeRage** 2022-07-21 23:01 UTC
