### ISSUE TITLE
Error parsing main.cvd file

### ISSUE THREAD

**Issue by BlackHoneyBear** [JusticeRage/Manalyze#20] opened 2017-08-06 16:09 UTC
C:\Users\50CAL\Manalyze\bin\yara_rules>python update_clamav_signatures.py
Downloading: main.cvd Bytes: 117892267
 Rule Win.Trojan.EOL-1 seems to be malformed. Skipping...

**Comment by JusticeRage** [comment] 2017-08-06 17:45
Closed as a duplicate of #21.

**Closed by JusticeRage** 2017-08-06 17:45 UTC
